include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters